[metadata]
name = amm-api-client
version = 0.1.0
author = Mattijs Snepvangers
description = AMM GraphQL API client
long_description = file: README.md
long_description_content_type = text/markdown
license = GPLv3
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GPLv3 License

[options]
packages = find:
package_dir =
    =src
install_requires =
    gql[all]>=3.5.0
    httpx>=0.27.0
    pydantic>=2.7.0

[options.packages.find]
where = src
